apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: madhuvmsftgosampleappnullcheck1 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: madhuvmsftgosampleappnullcheck1 
    spec:
      containers:
        - name: madhuvmsftgosampleappnullcheck1 
          image: desattiracr.azurecr.io/madhuvmsftgosampleappnullcheck1 
          ports:
          - containerPort: 80