apiVersion: v1
kind: Service
metadata:
    name: madhuvmsftgosampleappnullcheck1
spec:
    type: LoadBalancer
    ports:
    - port: 80 
    selector:
        app: madhuvmsftgosampleappnullcheck1