apiVersion: v1
kind: Service
metadata:
    name: madhuvmsftgosampleappvithati2
spec:
    type: LoadBalancer
    ports:
    - port: 80 
    selector:
        app: madhuvmsftgosampleappvithati2
